const path = require('path');
const PDFDocument = require('pdfkit');
const InferenceJob = require('../models/InferenceJob');
const ActionItem = require('../models/ActionItem');
const { validateWorkspaceAccess, canAccessAllWorkspaces } = require('../utils/workspaceScoping');
const {
  buildSurveyFromJobs,
  inspectFilter,
  resolveClassNamesForJobs,
  readMetadata,
} = require('./mobileInspectSurveyController');
const { resolveInferenceImagePath } = require('../utils/resolveInferenceImagePath');
const auditService = require('../services/auditService');

const MAX_PHOTOS_PER_AREA = 3;
const PHOTO_WIDTH = 150;
const CLOSED_STATUSES = ['approved', 'rejected', 'completed'];

function formatPct(n) {
  return typeof n === 'number' && Number.isFinite(n) ? `${n.toFixed(2)}%` : '—';
}

function formatDate(d) {
  return d ? new Date(d).toLocaleDateString() : '—';
}

/** Filenames of a job's result images, read from its metadata.json. */
function jobImageFilenames(job) {
  const metadata = readMetadata(job);
  if (!metadata) return [];
  const list = metadata.images || metadata.files || [];
  return list
    .filter((f) => !f.fileType || f.fileType === 'image')
    .map((f) => path.basename(String(f.filePath || '')))
    .filter(Boolean);
}

function ensureSpace(doc, needed) {
  if (doc.y + needed > doc.page.height - doc.page.margins.bottom) {
    doc.addPage();
  }
}

/**
 * GET /api/mobile-inspect/survey/pdf?company=&project=&surveyName=
 *
 * Streams a PDF report for one survey: location, photos, change since the
 * previous visit, severity, and any approved action, per area — plus a
 * summary of open/overdue actions for the project.
 */
const exportSurveyPdf = async (req, res) => {
  try {
    const company = String(req.query.company || req.user?.company || '').trim();
    const project = String(req.query.project || '').trim();
    const surveyName = String(req.query.surveyName || '').trim();

    if (!company || !project || !surveyName) {
      return res.status(400).json({
        error: 'Missing required query parameters',
        required: ['company', 'project', 'surveyName'],
      });
    }

    if (!canAccessAllWorkspaces(req.user)) {
      const access = validateWorkspaceAccess(req.user, company);
      if (!access.allowed) {
        return res.status(403).json({
          error: 'Permission denied',
          message: access.error || 'You do not have access to this workspace',
        });
      }
    }

    const jobs = await InferenceJob.find(inspectFilter(company, project, { surveyName }))
      .sort({ createdAt: -1 })
      .lean();

    if (!jobs.length) {
      return res.status(404).json({ error: 'Survey not found', company, project, surveyName });
    }

    const jobsById = new Map(jobs.map((j) => [j.inferenceId, j]));
    const classNames = await resolveClassNamesForJobs(jobs);
    const survey = buildSurveyFromJobs(surveyName, jobs, classNames);

    const actions = await ActionItem.find({ company, project, surveyName }).sort({ createdAt: -1 }).lean();
    const approvedByRegion = new Map();
    for (const action of actions) {
      if (!CLOSED_STATUSES.includes(action.status) || action.status === 'rejected') continue;
      if (!action.regionName) continue;
      if (!approvedByRegion.has(action.regionName)) approvedByRegion.set(action.regionName, []);
      approvedByRegion.get(action.regionName).push(action);
    }
    const now = Date.now();
    const openActions = actions.filter((a) => !CLOSED_STATUSES.includes(a.status));

    const safeName = surveyName.replace(/[^a-z0-9]+/gi, '_').replace(/^_+|_+$/g, '') || 'survey';
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}_report.pdf"`);

    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    doc.pipe(res);

    // --- Cover ---
    doc.fontSize(20).text('Corrosion Survey Report', { align: 'center' });
    doc.moveDown(1.5);
    doc.fontSize(12);
    doc.text(`Vessel (project): ${project}`);
    doc.text(`Company: ${company}`);
    doc.text(`Survey: ${surveyName}`);
    doc.text(`Generated: ${new Date().toLocaleString()}`);
    doc.text(`Generated by: ${req.user?.email || req.user?.id || 'unknown'}`);
    doc.text(`Overall mean corrosion: ${formatPct(survey.overallMeanCorrosionPercent)}`);
    doc.text(`Areas inspected: ${survey.partCount} (${survey.completedPartCount} completed)`);

    // --- Per-area sections ---
    for (const part of survey.parts) {
      doc.addPage();
      doc.fontSize(16).text(`Area: ${part.regionName}`);
      doc.moveDown(0.5);

      doc.fontSize(11);
      doc.text(`Location: ${part.regionName}`);
      doc.text(`Corrosion: ${formatPct(part.meanCorrosionPercent)}`);
      doc.text(`Severity: ${part.severityBand ? part.severityBand.toUpperCase() : 'N/A'}`);
      if (part.changeFromPrevious) {
        const delta = part.changeFromPrevious.delta;
        const sign = delta > 0 ? '+' : '';
        doc.text(
          `Change since previous visit: ${sign}${delta.toFixed(2)}% (previously ${formatPct(
            part.changeFromPrevious.previousMeanCorrosionPercent
          )})`
        );
      } else {
        doc.text('Change since previous visit: no prior completed visit to compare');
      }
      doc.moveDown(0.5);

      doc.fontSize(11).text('Approved action:', { underline: true });
      const approved = approvedByRegion.get(part.regionName) || [];
      if (approved.length) {
        for (const action of approved) {
          doc.fontSize(11).text(`- ${action.title} (approved by ${action.approvedBy || 'unknown'} on ${formatDate(action.approvedAt)})`);
          if (action.description) {
            doc.fontSize(10).fillColor('gray').text(action.description, { indent: 14 });
            doc.fillColor('black');
          }
        }
      } else {
        doc.fontSize(11).text('No approved action on file.');
      }
      doc.moveDown();

      // --- Photos ---
      const job = part.latestCompleted ? jobsById.get(part.latestCompleted.inferenceId) : null;
      if (job) {
        const filenames = jobImageFilenames(job).slice(0, MAX_PHOTOS_PER_AREA);
        if (filenames.length) {
          ensureSpace(doc, PHOTO_WIDTH + 20);
          let x = doc.x;
          const y = doc.y;
          for (const filename of filenames) {
            const resolved = resolveInferenceImagePath(job, filename);
            if (!resolved) continue;
            try {
              doc.image(resolved.imagePath, x, y, { width: PHOTO_WIDTH });
              x += PHOTO_WIDTH + 10;
            } catch (imgErr) {
              console.warn(`[pdf-export] Could not embed image ${filename}:`, imgErr.message);
            }
          }
          doc.y = y + PHOTO_WIDTH + 10;
          doc.x = doc.page.margins.left;
        }
      }
    }

    // --- Open actions / overdue reviews summary ---
    doc.addPage();
    doc.fontSize(16).text('Open Actions & Overdue Reviews');
    doc.moveDown();
    doc.fontSize(10);
    if (!openActions.length) {
      doc.text('No open actions for this project.');
    } else {
      for (const action of openActions) {
        const overdue = action.dueDate && new Date(action.dueDate).getTime() < now;
        ensureSpace(doc, 30);
        doc.fillColor(overdue ? 'red' : 'black').text(
          `${action.regionName || '(no area)'} — ${action.severity.toUpperCase()} — ${action.status}` +
            ` — due ${formatDate(action.dueDate)}${overdue ? ' (OVERDUE)' : ''}` +
            ` — assigned: ${action.assignedTo || '—'}`
        );
        doc.fillColor('black').fontSize(9).text(action.title, { indent: 10 });
        doc.fontSize(10);
      }
    }

    doc.end();

    auditService.logAction({
      action: 'view',
      resourceType: 'action_item',
      resourceId: surveyName,
      details: { company, project, exportType: 'pdf' },
      req,
    });
  } catch (error) {
    console.error('Error exporting survey PDF:', error);
    if (!res.headersSent) {
      return res.status(500).json({ error: 'Internal server error', message: error.message });
    }
    res.end();
  }
};

module.exports = { exportSurveyPdf };
